# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sdm710-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter pyxis vela,$(TARGET_DEVICE)),)

endif
